apiVersion: v1
kind: Secret
metadata:
  name: konflux-devlake-secrets
  namespace: konflux-devlake
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: ui
type: Opaque
data: {}