apiVersion: v1
kind: ServiceAccount
metadata:
  name: konflux-mcp-server
  namespace: konflux-devlake
  labels:
    app: konflux-mcp-server
    component: mcp-server
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: ui
  annotations:
    openshift.io/display-name: "Konflux MCP Server"
    openshift.io/description: "Service account for Konflux DevLake MCP Server" 