name: MCP E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      test_models:
        description: "Comma-separated models (e.g. gemini/gemini-2.5-pro,gpt-4o,claude-3-5-sonnet-20240620)"
        required: false
        default: "gemini/gemini-2.5-pro,gpt-4o,claude-3-5-sonnet-20240620"

permissions:
  contents: read

jobs:
  e2e-secrets-precheck:
    name: E2E secret precheck
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Fail if no LLM API keys set
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ] && [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ] && [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "::error::No LLM API keys set. Set at least one of OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY."
            exit 1
          fi
  e2e-tests:
    name: E2E Tests (${{ matrix.model }})
    needs: e2e-secrets-precheck
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: gemini/gemini-2.5-pro
            require_secret: GEMINI_API_KEY
          - model: gpt-4o
            require_secret: OPENAI_API_KEY
          - model: claude-3-5-sonnet-20240620
            require_secret: ANTHROPIC_API_KEY
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: lake
          MYSQL_USER: devlake
          MYSQL_PASSWORD: devlake_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ptest_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --tmpfs /var/lib/mysql:rw,noexec,nosuid,size=1024m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Select model if required secret is present
        id: select
        shell: bash
        run: |
          RUN=false
          REQ=${{ matrix.require_secret }}
          if [ -z "$REQ" ]; then
            RUN=true
          elif [ "$REQ" = "OPENAI_API_KEY" ] && [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            RUN=true
          elif [ "$REQ" = "ANTHROPIC_API_KEY" ] && [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            RUN=true
          elif [ "$REQ" = "GEMINI_API_KEY" ] && [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
            RUN=true
          fi
          echo "run=$RUN" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
        if: steps.select.outputs.run == 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.select.outputs.run == 'true'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -P3306 -uroot -ptest_password --silent; then
              echo "MySQL is ready!"; break; fi
            echo "Waiting for MySQL... ($i/30)"; sleep 2;
          done
        if: steps.select.outputs.run == 'true'

      - name: Initialize test database schema and data
        run: |
          mysql -h127.0.0.1 -P3306 -uroot -ptest_password -e "DROP DATABASE IF EXISTS lake; CREATE DATABASE lake;"
          mysql -h127.0.0.1 -P3306 -uroot -ptest_password lake < testdata/mysql/01-schema.sql
          mysql -h127.0.0.1 -P3306 -uroot -ptest_password lake < testdata/mysql/02-test-data.sql
        if: steps.select.outputs.run == 'true'

      - name: Run E2E tests for model
        env:
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_PORT: 3306
          TEST_DB_USER: devlake
          TEST_DB_PASSWORD: devlake_password
          TEST_DB_NAME: lake
          LITELLM_LOGGING: "0"
          LITELLM_DISABLE_LOGGING: "1"
          LITELLM_VERBOSE: "0"
          LITELLM_LOGGING_QUEUE: "0"
          E2E_DB_WAIT_SECS: "45"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          E2E_TEST_MODELS: ${{ matrix.model }}
        run: |
          pytest tests/e2e -vv --maxfail=1 --tb=short
        if: steps.select.outputs.run == 'true'

      - name: Summarize E2E results (executed)
        if: always() && steps.select.outputs.run == 'true'
        run: |
          echo "## E2E Tests Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Model**: ${{ matrix.model }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Suite**: Database, Incidents, Deployments (outcome-based assertions)" >> $GITHUB_STEP_SUMMARY

      - name: Summarize E2E results (skipped - missing secret)
        if: always() && steps.select.outputs.run != 'true'
        run: |
          echo "## E2E Tests Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Model**: ${{ matrix.model }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: skipped (missing required secret: ${{ matrix.require_secret }})" >> $GITHUB_STEP_SUMMARY
